/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

/**
 *
 * @author rtiam
 */
public class MainFrame extends javax.swing.JFrame {

    private dialogue.Dialogue dialogue;
    private boundary.PanelPlateau plateau;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        plateau = new boundary.PanelPlateau();
        PanelPlateau.setLayout(new java.awt.BorderLayout());
        PanelPlateau.add(plateau, java.awt.BorderLayout.CENTER);
    }

    public void setDialogue(dialogue.Dialogue dialogue) {
        this.dialogue = dialogue;
        de1.setOnAnimationFinie(() -> dialogue.animationDeTerminee());
        de2.setOnAnimationFinie(() -> dialogue.animationDeTerminee());
        plateau.setOnPionPlace(caseNumero -> dialogue.pionPlaceCorrectement(caseNumero));
    }

    public void activerBouton(boolean actif) {
        boutonLancer.setEnabled(actif);
    }

    public void afficherDes(int r1, int r2) {
        de1.lancerAnimation(r1);
        de2.lancerAnimation(r2);
    }

    public void activerDrag(int cible) {
        plateau.activerDrag(cible);
    }

    public void deplacerPion(int joueur, int caseNumero, java.awt.Color couleur) {
        plateau.deplacerPion(joueur, caseNumero, couleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHaut = new javax.swing.JPanel();
        JPanelDes = new javax.swing.JPanel();
        boutonLancer = new javax.swing.JButton();
        de1 = new boundary.PanelDe();
        de2 = new boundary.PanelDe();
        JPanelInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();
        PanelPlateau = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelHaut.setLayout(new java.awt.BorderLayout());

        JPanelDes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPanelDes.setPreferredSize(new java.awt.Dimension(190, 150));

        boutonLancer.setText("Lancer les dés");
        boutonLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonLancerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout de1Layout = new javax.swing.GroupLayout(de1);
        de1.setLayout(de1Layout);
        de1Layout.setHorizontalGroup(
            de1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        de1Layout.setVerticalGroup(
            de1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout de2Layout = new javax.swing.GroupLayout(de2);
        de2.setLayout(de2Layout);
        de2Layout.setHorizontalGroup(
            de2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        de2Layout.setVerticalGroup(
            de2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPanelDesLayout = new javax.swing.GroupLayout(JPanelDes);
        JPanelDes.setLayout(JPanelDesLayout);
        JPanelDesLayout.setHorizontalGroup(
            JPanelDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDesLayout.createSequentialGroup()
                .addGroup(JPanelDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(de2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelDesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(boutonLancer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelDesLayout.setVerticalGroup(
            JPanelDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(de1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(de2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonLancer)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelHaut.add(JPanelDes, java.awt.BorderLayout.WEST);

        JPanelInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPanelInfo.setPreferredSize(new java.awt.Dimension(300, 150));
        JPanelInfo.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        Titre.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        Titre.setForeground(new java.awt.Color(10, 10, 10));
        Titre.setText("Isla de la muerte");
        Titre.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel1.add(Titre);

        InfoButton.setBackground(new java.awt.Color(186, 224, 255));
        InfoButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        InfoButton.setText("?");
        InfoButton.setToolTipText("Afficher les règles du jeu");
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(InfoButton);

        JPanelInfo.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelHaut.add(JPanelInfo, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelHaut, java.awt.BorderLayout.NORTH);

        PanelPlateau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelPlateauLayout = new javax.swing.GroupLayout(PanelPlateau);
        PanelPlateau.setLayout(PanelPlateauLayout);
        PanelPlateauLayout.setHorizontalGroup(
            PanelPlateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        PanelPlateauLayout.setVerticalGroup(
            PanelPlateauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPlateau, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Melanie
    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
       javax.swing.JOptionPane.showMessageDialog(
        this,
        "Règles du jeu des pirates :\n"
        + "-2 joueurs\n"
        + "-30 cases\n"
        + "-5 points de vie maximum\n"
        + "-Le premier à la dernière case gagne ou on gagne si l’adversaire n’a plus de vie\n\n"
        + "Cases spéciales :\n"
        + "-Case Bombe\n"
        + "-Case mystère\n"
        + "-Chute de noix de coco\n"
        + "BONNE CHANCE",
        "Règles du jeu",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_InfoButtonActionPerformed

    private void boutonLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonLancerActionPerformed
        if (dialogue != null)
            dialogue.lancerDes();
    }//GEN-LAST:event_boutonLancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoButton;
    private javax.swing.JPanel JPanelDes;
    private javax.swing.JPanel JPanelInfo;
    private javax.swing.JPanel PanelHaut;
    private javax.swing.JPanel PanelPlateau;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton boutonLancer;
    private boundary.PanelDe de1;
    private boundary.PanelDe de2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
