/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author nolawi
 */
// Nolawi
public class PanelCase extends javax.swing.JPanel {

    public static final String NORMALE = "NORMALE";
    public static final String BOMBE   = "BOMBE";
    public static final String COCO    = "COCO";
    public static final String MYSTERE = "MYSTERE";

    public static final String HORIZONTAL       = "HORIZONTAL";
    public static final String COIN_DROITE_HAUT = "COIN_DROITE_HAUT";
    public static final String COIN_DROITE_BAS  = "COIN_DROITE_BAS";
    public static final String COIN_GAUCHE_HAUT = "COIN_GAUCHE_HAUT";
    public static final String COIN_GAUCHE_BAS  = "COIN_GAUCHE_BAS";

    private static final Color COULEUR_BORD    = new Color(173, 216, 230);
    private static final Color COULEUR_MILIEU  = new Color(245, 225, 180);
    private static final Color COULEUR_ROUGE   = new Color(200, 60, 60);
    private static final Color COULEUR_VERTE   = new Color(60, 180, 60);

    private int numero;
    private String type;
    private String direction;
    private boolean contientJoueur;
    private Color couleurPion;
    private Color highlight;

    public PanelCase() {
        initComponents();
    }

    public PanelCase(int numero, String type, String direction) {
        initComponents();
        this.numero    = numero;
        this.type      = type;
        this.direction = direction;
        setPreferredSize(new Dimension(90, 90));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setHighlight(Color couleur) {
        this.highlight = couleur;
        repaint();
    }

    public void clearHighlight() {
        this.highlight = null;
        repaint();
    }

    public void setContientJoueur(boolean contient, Color couleur) {
        this.contientJoueur = contient;
        this.couleurPion = couleur;
        repaint();
    }

    public int getNumero() {
        return numero;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int w  = getWidth();
        int h  = getHeight();
        int s  = Math.min(w, h) / 4;  // strip size, same for all sides
        int cx = w / 2;
        int cy = h / 2;

        // 1. fill everything beige first
        g2d.setColor(COULEUR_MILIEU);
        g2d.fillRect(0, 0, w, h);

        // 2. draw the two strips based on direction
        g2d.setColor(COULEUR_BORD);
        switch (direction == null ? HORIZONTAL : direction) {
            case COIN_DROITE_HAUT:
                g2d.fillRect(0, 0, w, s);        // top
                g2d.fillRect(w - s, 0, s, h);    // right
                g2d.fillRect(0, h-s, s, h-s);    // left-bottom
                break;
            case COIN_DROITE_BAS:
                g2d.fillRect(w - s, 0, s, h);    // right
                g2d.fillRect(0, h - s, w, s);    // bottom
                g2d.fillRect(0, 0, s, s);        // left-up
                
                break;
            case COIN_GAUCHE_HAUT:
                g2d.fillRect(0, 0, w, s);        // top
                g2d.fillRect(0, 0, s, h);        // left
                break;
            case COIN_GAUCHE_BAS:
                g2d.fillRect(0, 0, s, h);        // left
                g2d.fillRect(0, h - s, w, s);    // bottom
                break;
            default:                             // HORIZONTAL
                g2d.fillRect(0, 0, w, s);        // top
                g2d.fillRect(0, h - s, w, s);    // bottom
                break; 
        }

        // 3. center line dashes
        float dashLen = w * 0.12f;
        float gapLen  = w * 0.10f;
        g2d.setColor(new Color(180, 160, 130));
        g2d.setStroke(new BasicStroke(
            Math.max(1, h / 30f),
            BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER,
            10, new float[]{dashLen, gapLen}, 0
        ));
        switch (direction == null ? HORIZONTAL : direction) {
            case COIN_DROITE_HAUT:
                g2d.drawLine(w/9, cy, cx, cy);           // horizontal: left → center
                g2d.drawLine(cx, cy, cx, 8*h/9);       // vertical:   center → bottom
                break;
            case COIN_DROITE_BAS:
                g2d.drawLine(cx, h/9, cx, cy);         // vertical:   top → center
                g2d.drawLine(cx, cy, w/9, cy);           // horizontal: center → left
                break;
            case COIN_GAUCHE_HAUT:
                g2d.drawLine(8*w/9, cy, cx, cy);       // horizontal: right → center
                g2d.drawLine(cx, cy, cx, 8*h/9);       // vertical:   center → bottom
                break;
            case COIN_GAUCHE_BAS:
                g2d.drawLine(cx, h/9, cx, cy);           // vertical:   top → center
                g2d.drawLine(cx, cy, 8*w/9, cy);           // horizontal: center → right
                break;
            default:
                g2d.drawLine(w / 9, cy, 8 * w / 9, cy);
                break;
        }


        // 4. black outer border
        g2d.setColor(Color.BLACK);
        g2d.setStroke(new BasicStroke(1));
        g2d.drawRect(0, 0, w - 1, h - 1);

        // 5. numero — white
        int fontSize = Math.max(9, s - 4);
        g2d.setFont(new Font("Arial", Font.BOLD, fontSize));
        g2d.setColor(Color.WHITE );
        g2d.drawString(String.valueOf(numero), 3, s - 2);

        if (null != type) // 6. icon centered in the case
        switch (type) {
            case BOMBE:
                dessinerBombe(g2d, cx, cy, h / 2);
                break;
            case COCO:
                dessinerCoco(g2d, cx, cy, h / 2);
                break;
            case MYSTERE:
                dessinerMystere(g2d, cx, cy, h / 2, w);
                break;
            default:
                break;
        }

        // 7. pion centered in the case
        if (contientJoueur) {
            int rayon = h / 6;
            g2d.setColor(couleurPion);
            g2d.fillOval(cx - rayon, cy - rayon, 2 * rayon, 2 * rayon);
            g2d.setColor(Color.BLACK);
            g2d.setStroke(new BasicStroke(2));
            g2d.drawOval(cx - rayon, cy - rayon, 2 * rayon, 2 * rayon);
        }

        // 8. highlight border drawn last
        if (highlight != null) {
            int b = 4;
            g2d.setColor(highlight);
            g2d.setStroke(new BasicStroke(b));
            g2d.drawRect(b / 2, b / 2, w - b, h - b);
        }
    }

    private void dessinerBombe(Graphics2D g2d, int cx, int cy, int midH) {
        int r = midH / 3;
        g2d.setColor(Color.DARK_GRAY);
        g2d.fillOval(cx - r, cy - r, 2 * r, 2 * r);
        int fuseH = r;
        g2d.setColor(new Color(80, 50, 20));
        g2d.setStroke(new BasicStroke(Math.max(2, r / 4)));
        g2d.drawLine(cx, cy - r, cx + fuseH / 2, cy - r - fuseH);
        int sparkR = Math.max(3, r / 3);
        g2d.setColor(Color.ORANGE);
        g2d.fillOval(cx + fuseH / 2 - sparkR / 2, cy - r - fuseH - sparkR / 2, sparkR, sparkR);
    }

    private void dessinerCoco(Graphics2D g2d, int cx, int cy, int midH) {
        int trunkH = (int)(midH * 0.7);
        int base   = cy + trunkH / 2;
        int haut   = base - trunkH;
        int leafLen = (int)(midH * 0.45);
        g2d.setColor(new Color(139, 90, 43));
        g2d.setStroke(new BasicStroke(Math.max(2, midH / 12)));
        g2d.drawLine(cx, base, cx - 3, haut);
        g2d.setColor(new Color(34, 139, 34));
        g2d.setStroke(new BasicStroke(Math.max(1, midH / 18)));
        g2d.drawLine(cx, haut, cx - leafLen, haut - leafLen / 2);
        g2d.drawLine(cx, haut, cx + leafLen, haut - leafLen / 3);
        g2d.drawLine(cx, haut, cx, haut - leafLen);
        int cocoR = Math.max(3, midH / 8);
        g2d.setColor(new Color(139, 90, 43));
        g2d.fillOval(cx - cocoR * 2, haut - cocoR / 2, cocoR * 2, cocoR * 2);
    }

    private void dessinerMystere(Graphics2D g2d, int cx, int cy, int midH, int w) {
        int cw   = w / 3;
        int ch   = midH / 2;
        int lidH = ch / 2;
        g2d.setColor(new Color(139, 90, 43));
        g2d.fillRect(cx - cw / 2, cy - ch / 2, cw, ch);
        g2d.setColor(new Color(101, 67, 33));
        g2d.fillRect(cx - cw / 2, cy - ch / 2 - lidH, cw, lidH);
        g2d.setColor(Color.BLACK);
        g2d.setStroke(new BasicStroke(1));
        g2d.drawRect(cx - cw / 2, cy - ch / 2, cw, ch);
        g2d.drawRect(cx - cw / 2, cy - ch / 2 - lidH, cw, lidH);
        int lockR = Math.max(3, cw / 8);
        g2d.setColor(new Color(255, 215, 0));
        g2d.fillOval(cx - lockR, cy - lockR, lockR * 2, lockR * 2);
    }
    public static void main(String[] args) {
        javax.swing.JFrame frame = new javax.swing.JFrame("Test PanelCase");
        frame.setLayout(new java.awt.GridLayout(2, 5, 0, 0));
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

        // row 1: straight cases
        frame.add(new PanelCase(1,  NORMALE,  HORIZONTAL));
        frame.add(new PanelCase(2,  NORMALE,  HORIZONTAL));
        frame.add(new PanelCase(3,  BOMBE,    HORIZONTAL));
        frame.add(new PanelCase(4,  NORMALE,  HORIZONTAL));
        frame.add(new PanelCase(5,  NORMALE,  COIN_DROITE_HAUT));
        // row 2: snake turn
        frame.add(new PanelCase(10, MYSTERE,  COIN_GAUCHE_HAUT));
        frame.add(new PanelCase(9,  NORMALE,  HORIZONTAL));
        frame.add(new PanelCase(8,  COCO,     HORIZONTAL));
        frame.add(new PanelCase(7,  NORMALE,  HORIZONTAL));
        frame.add(new PanelCase(6,  NORMALE,  COIN_DROITE_BAS));

        frame.setSize(600, 240);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
