/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

/**
 *
 * @author beman
 */
public class PanelCoco extends javax.swing.JPanel {

    /**
     * Creates new form PanelCoco
     */
    public PanelCoco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDemiCocoGauche1 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit1 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche2 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit2 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoDroit3 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche3 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoGauche4 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit4 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche5 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit5 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoDroit6 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche6 = new presentation.PanelDemiCocoGauche();

        javax.swing.GroupLayout panelDemiCocoGauche1Layout = new javax.swing.GroupLayout(panelDemiCocoGauche1);
        panelDemiCocoGauche1.setLayout(panelDemiCocoGauche1Layout);
        panelDemiCocoGauche1Layout.setHorizontalGroup(
            panelDemiCocoGauche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        panelDemiCocoGauche1Layout.setVerticalGroup(
            panelDemiCocoGauche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit1Layout = new javax.swing.GroupLayout(panelDemiCocoDroit1);
        panelDemiCocoDroit1.setLayout(panelDemiCocoDroit1Layout);
        panelDemiCocoDroit1Layout.setHorizontalGroup(
            panelDemiCocoDroit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoDroit1Layout.setVerticalGroup(
            panelDemiCocoDroit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche2Layout = new javax.swing.GroupLayout(panelDemiCocoGauche2);
        panelDemiCocoGauche2.setLayout(panelDemiCocoGauche2Layout);
        panelDemiCocoGauche2Layout.setHorizontalGroup(
            panelDemiCocoGauche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche2Layout.setVerticalGroup(
            panelDemiCocoGauche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit2Layout = new javax.swing.GroupLayout(panelDemiCocoDroit2);
        panelDemiCocoDroit2.setLayout(panelDemiCocoDroit2Layout);
        panelDemiCocoDroit2Layout.setHorizontalGroup(
            panelDemiCocoDroit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoDroit2Layout.setVerticalGroup(
            panelDemiCocoDroit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit3Layout = new javax.swing.GroupLayout(panelDemiCocoDroit3);
        panelDemiCocoDroit3.setLayout(panelDemiCocoDroit3Layout);
        panelDemiCocoDroit3Layout.setHorizontalGroup(
            panelDemiCocoDroit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        panelDemiCocoDroit3Layout.setVerticalGroup(
            panelDemiCocoDroit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche3Layout = new javax.swing.GroupLayout(panelDemiCocoGauche3);
        panelDemiCocoGauche3.setLayout(panelDemiCocoGauche3Layout);
        panelDemiCocoGauche3Layout.setHorizontalGroup(
            panelDemiCocoGauche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche3Layout.setVerticalGroup(
            panelDemiCocoGauche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche4Layout = new javax.swing.GroupLayout(panelDemiCocoGauche4);
        panelDemiCocoGauche4.setLayout(panelDemiCocoGauche4Layout);
        panelDemiCocoGauche4Layout.setHorizontalGroup(
            panelDemiCocoGauche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche4Layout.setVerticalGroup(
            panelDemiCocoGauche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        panelDemiCocoDroit4.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout panelDemiCocoDroit4Layout = new javax.swing.GroupLayout(panelDemiCocoDroit4);
        panelDemiCocoDroit4.setLayout(panelDemiCocoDroit4Layout);
        panelDemiCocoDroit4Layout.setHorizontalGroup(
            panelDemiCocoDroit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        panelDemiCocoDroit4Layout.setVerticalGroup(
            panelDemiCocoDroit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche5Layout = new javax.swing.GroupLayout(panelDemiCocoGauche5);
        panelDemiCocoGauche5.setLayout(panelDemiCocoGauche5Layout);
        panelDemiCocoGauche5Layout.setHorizontalGroup(
            panelDemiCocoGauche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        panelDemiCocoGauche5Layout.setVerticalGroup(
            panelDemiCocoGauche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit5Layout = new javax.swing.GroupLayout(panelDemiCocoDroit5);
        panelDemiCocoDroit5.setLayout(panelDemiCocoDroit5Layout);
        panelDemiCocoDroit5Layout.setHorizontalGroup(
            panelDemiCocoDroit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        panelDemiCocoDroit5Layout.setVerticalGroup(
            panelDemiCocoDroit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit6Layout = new javax.swing.GroupLayout(panelDemiCocoDroit6);
        panelDemiCocoDroit6.setLayout(panelDemiCocoDroit6Layout);
        panelDemiCocoDroit6Layout.setHorizontalGroup(
            panelDemiCocoDroit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        panelDemiCocoDroit6Layout.setVerticalGroup(
            panelDemiCocoDroit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche6Layout = new javax.swing.GroupLayout(panelDemiCocoGauche6);
        panelDemiCocoGauche6.setLayout(panelDemiCocoGauche6Layout);
        panelDemiCocoGauche6Layout.setHorizontalGroup(
            panelDemiCocoGauche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        panelDemiCocoGauche6Layout.setVerticalGroup(
            panelDemiCocoGauche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelDemiCocoGauche6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(panelDemiCocoDroit6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDemiCocoDroit6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(panelDemiCocoGauche6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit1;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit2;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit3;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit4;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit5;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit6;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche1;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche2;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche3;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche4;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche5;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche6;
    // End of variables declaration//GEN-END:variables
}
