/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author beman
 */
public class PanelCoco extends javax.swing.JPanel {

    /**
     * Creates new form PanelCoco
     * @param value
     */
    public PanelCoco(int value) {
        initComponents();
        setTextPV(value);
    }
    
    private void setTextPV(int value){
        String text = Integer.toString(value);
        jLabel8.setText(text);
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDemiCocoGauche1 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit1 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche2 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit2 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoDroit3 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche3 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoGauche4 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit4 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche5 = new presentation.PanelDemiCocoGauche();
        panelDemiCocoDroit5 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoDroit6 = new presentation.PanelDemiCocoDroit();
        panelDemiCocoGauche6 = new presentation.PanelDemiCocoGauche();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout panelDemiCocoGauche1Layout = new javax.swing.GroupLayout(panelDemiCocoGauche1);
        panelDemiCocoGauche1.setLayout(panelDemiCocoGauche1Layout);
        panelDemiCocoGauche1Layout.setHorizontalGroup(
            panelDemiCocoGauche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        panelDemiCocoGauche1Layout.setVerticalGroup(
            panelDemiCocoGauche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit1Layout = new javax.swing.GroupLayout(panelDemiCocoDroit1);
        panelDemiCocoDroit1.setLayout(panelDemiCocoDroit1Layout);
        panelDemiCocoDroit1Layout.setHorizontalGroup(
            panelDemiCocoDroit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoDroit1Layout.setVerticalGroup(
            panelDemiCocoDroit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche2Layout = new javax.swing.GroupLayout(panelDemiCocoGauche2);
        panelDemiCocoGauche2.setLayout(panelDemiCocoGauche2Layout);
        panelDemiCocoGauche2Layout.setHorizontalGroup(
            panelDemiCocoGauche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche2Layout.setVerticalGroup(
            panelDemiCocoGauche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit2Layout = new javax.swing.GroupLayout(panelDemiCocoDroit2);
        panelDemiCocoDroit2.setLayout(panelDemiCocoDroit2Layout);
        panelDemiCocoDroit2Layout.setHorizontalGroup(
            panelDemiCocoDroit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoDroit2Layout.setVerticalGroup(
            panelDemiCocoDroit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit3Layout = new javax.swing.GroupLayout(panelDemiCocoDroit3);
        panelDemiCocoDroit3.setLayout(panelDemiCocoDroit3Layout);
        panelDemiCocoDroit3Layout.setHorizontalGroup(
            panelDemiCocoDroit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        panelDemiCocoDroit3Layout.setVerticalGroup(
            panelDemiCocoDroit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche3Layout = new javax.swing.GroupLayout(panelDemiCocoGauche3);
        panelDemiCocoGauche3.setLayout(panelDemiCocoGauche3Layout);
        panelDemiCocoGauche3Layout.setHorizontalGroup(
            panelDemiCocoGauche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche3Layout.setVerticalGroup(
            panelDemiCocoGauche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche4Layout = new javax.swing.GroupLayout(panelDemiCocoGauche4);
        panelDemiCocoGauche4.setLayout(panelDemiCocoGauche4Layout);
        panelDemiCocoGauche4Layout.setHorizontalGroup(
            panelDemiCocoGauche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelDemiCocoGauche4Layout.setVerticalGroup(
            panelDemiCocoGauche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        panelDemiCocoDroit4.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout panelDemiCocoDroit4Layout = new javax.swing.GroupLayout(panelDemiCocoDroit4);
        panelDemiCocoDroit4.setLayout(panelDemiCocoDroit4Layout);
        panelDemiCocoDroit4Layout.setHorizontalGroup(
            panelDemiCocoDroit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        panelDemiCocoDroit4Layout.setVerticalGroup(
            panelDemiCocoDroit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche5Layout = new javax.swing.GroupLayout(panelDemiCocoGauche5);
        panelDemiCocoGauche5.setLayout(panelDemiCocoGauche5Layout);
        panelDemiCocoGauche5Layout.setHorizontalGroup(
            panelDemiCocoGauche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        panelDemiCocoGauche5Layout.setVerticalGroup(
            panelDemiCocoGauche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit5Layout = new javax.swing.GroupLayout(panelDemiCocoDroit5);
        panelDemiCocoDroit5.setLayout(panelDemiCocoDroit5Layout);
        panelDemiCocoDroit5Layout.setHorizontalGroup(
            panelDemiCocoDroit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        panelDemiCocoDroit5Layout.setVerticalGroup(
            panelDemiCocoDroit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoDroit6Layout = new javax.swing.GroupLayout(panelDemiCocoDroit6);
        panelDemiCocoDroit6.setLayout(panelDemiCocoDroit6Layout);
        panelDemiCocoDroit6Layout.setHorizontalGroup(
            panelDemiCocoDroit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        panelDemiCocoDroit6Layout.setVerticalGroup(
            panelDemiCocoDroit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDemiCocoGauche6Layout = new javax.swing.GroupLayout(panelDemiCocoGauche6);
        panelDemiCocoGauche6.setLayout(panelDemiCocoGauche6Layout);
        panelDemiCocoGauche6Layout.setHorizontalGroup(
            panelDemiCocoGauche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        panelDemiCocoGauche6Layout.setVerticalGroup(
            panelDemiCocoGauche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Vous êtes sur une case chute de noix de coco!");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("Une noix de coco vous est tombée sur la tête!");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setText("Vous perdez");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 0));
        jLabel4.setText("Vous gagnez une noix de coco :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("Retirez un dé à l'adversaire.");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 0));
        jLabel6.setText("(Valable pour un seul tour.)");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("points de vie.");

        jLabel8.setForeground(new java.awt.Color(102, 204, 0));
        jLabel8.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDemiCocoGauche6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)))
                .addComponent(panelDemiCocoDroit6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDemiCocoDroit6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(panelDemiCocoGauche6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 47, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit1;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit2;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit3;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit4;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit5;
    private presentation.PanelDemiCocoDroit panelDemiCocoDroit6;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche1;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche2;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche3;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche4;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche5;
    private presentation.PanelDemiCocoGauche panelDemiCocoGauche6;
    // End of variables declaration//GEN-END:variables
}
