/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Yoakin
 */




//Yoakin
public class PanelDemarrage extends javax.swing.JPanel {
    private JTextField champNomJoueur1;
    private JTextField champNomJoueur2;
    private JButton boutonJouer;
    /**
     * Creates new form PanelDemarrage
     */
    public PanelDemarrage(MainFrame mainFrame) {
        setLayout(new GridLayout(7, 1));
        
        // Pemret de créer des marges invisibles pour que les éléments ne collent pas aux bords
        setBorder(BorderFactory.createEmptyBorder(20, 200, 50, 100));
        
        //Titre
        JLabel labelTitre = new JLabel("Isla de la Muerte", SwingConstants.CENTER);
        labelTitre.setFont(new Font("Calibri", Font.ITALIC, 52));
        add(labelTitre);
        
        // Label Joueur 1 (centré sur la page, texte aligné à gauche)
        JLabel labelJ1 = new JLabel("Nom du Pirate 1 :", SwingConstants.CENTER);
        add(labelJ1);
        
        // Champ texte Joueur 1 (centré sur la page)
        JPanel panelFieldJ1 = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        champNomJoueur1 = new JTextField(15);
        champNomJoueur1.setPreferredSize(new Dimension(300, 30));
        panelFieldJ1.add(champNomJoueur1);
        add(panelFieldJ1);
        
        // Label Joueur 2
        JPanel panelLabelJ2 = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        JLabel labelJ2 = new JLabel("Nom du Pirate 2 :");
        panelLabelJ2.add(labelJ2);
        add(panelLabelJ2);
        
        // Champ texte Joueur 2
        JPanel panelFieldJ2 = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        champNomJoueur2 = new JTextField(15);
        champNomJoueur2.setPreferredSize(new Dimension(300, 30));
        panelFieldJ2.add(champNomJoueur2);
        add(panelFieldJ2);
        
        
        //JButton : Jouer
        JPanel panelBouton = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        boutonJouer = new JButton("Jouer");
        boutonJouer.addActionListener(e -> {
            String nom1 = champNomJoueur1.getText().trim();
            String nom2 = champNomJoueur2.getText().trim();
            if (nom1.isEmpty() || nom2.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Veuillez saisir les noms des deux pirates !",
                    "Noms manquants", JOptionPane.WARNING_MESSAGE);
                return; // En revient en arrière pour remplir les cases à nouveaux
            }
            mainFrame.basculerVersJeu(nom1, nom2);
        });
        //Permet de clicker "Jouer" avec la touche "Entrez"
        champNomJoueur1.addActionListener(e -> boutonJouer.doClick());
        champNomJoueur2.addActionListener(e -> boutonJouer.doClick());
        
        
        panelBouton.add(boutonJouer);
        add(panelBouton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
