/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import java.awt.Window;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author oscar
 */
public class PanelMystere extends javax.swing.JPanel {

    private String endText = " NO ";

    /**
     * Creates new form PanelMystere
     */
    public PanelMystere() {
        initComponents();
    }

    public PanelMystere(int effect, int value) {
        initComponents();
        this.panelCarte1.setEffectAndValue(effect, value);
        this.panelCarte2.setEffectAndValue(effect, value);
        this.panelCarte3.setEffectAndValue(effect, value);
        setEndText(effect, value);
    }

    public void setEffectAndValue(int effect, int value) {
        this.panelCarte1.setEffectAndValue(effect, value);
        this.panelCarte2.setEffectAndValue(effect, value);
        this.panelCarte3.setEffectAndValue(effect, value);
        setEndText(effect, value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarte1 = new presentation.PanelCarte();
        panelCarte2 = new presentation.PanelCarte();
        panelCarte3 = new presentation.PanelCarte();
        jLabelTop = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(648, 460));

        panelCarte1.setPreferredSize(new java.awt.Dimension(200, 280));
        panelCarte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCarte1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCarte1Layout = new javax.swing.GroupLayout(panelCarte1);
        panelCarte1.setLayout(panelCarte1Layout);
        panelCarte1Layout.setHorizontalGroup(
            panelCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelCarte1Layout.setVerticalGroup(
            panelCarte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        panelCarte2.setPreferredSize(new java.awt.Dimension(200, 280));
        panelCarte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCarte2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCarte2Layout = new javax.swing.GroupLayout(panelCarte2);
        panelCarte2.setLayout(panelCarte2Layout);
        panelCarte2Layout.setHorizontalGroup(
            panelCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelCarte2Layout.setVerticalGroup(
            panelCarte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        panelCarte3.setPreferredSize(new java.awt.Dimension(200, 280));
        panelCarte3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCarte3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCarte3Layout = new javax.swing.GroupLayout(panelCarte3);
        panelCarte3.setLayout(panelCarte3Layout);
        panelCarte3Layout.setHorizontalGroup(
            panelCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        panelCarte3Layout.setVerticalGroup(
            panelCarte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jLabelTop.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabelTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTop.setText("Choisissez une carte...");
        jLabelTop.setName(""); // NOI18N

        jLabelEnd.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabelEnd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnd.setText("Le tresore vous attend");
        jLabelEnd.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelEnd)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabelTop.getAccessibleContext().setAccessibleParent(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelCarte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCarte1MouseClicked
        handleCardClick(panelCarte1);
    }//GEN-LAST:event_panelCarte1MouseClicked

    private void panelCarte2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCarte2MouseClicked
        handleCardClick(panelCarte2);
    }//GEN-LAST:event_panelCarte2MouseClicked

    private void panelCarte3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCarte3MouseClicked
        handleCardClick(panelCarte3);
    }//GEN-LAST:event_panelCarte3MouseClicked

    private void handleCardClick(PanelCarte selectedCarte){
        if (!selectedCarte.enableFlip) {
            return;
        }
        selectedCarte.flipCard();
        disableAllCards();
        showEndText();
        
        //wait 1.5s, then close the window
        javax.swing.Timer closeTime = new Timer(2000, e -> {
            Window window = SwingUtilities.getWindowAncestor(this);
            if(window!=null)
                window.dispose();
        });
        
        closeTime.setRepeats(false);
        closeTime.start();
    }
    
    private void showEndText() {
        this.jLabelEnd.setText(endText);
    }

    private void disableAllCards() {
        this.panelCarte3.enableFlip = false;
        this.panelCarte2.enableFlip = (false);
        this.panelCarte1.enableFlip = false;
    }

    private void setEndText(int effect, int value) {
        switch (effect) {
            case 2:
                endText = "Vous gagnez " + String.valueOf(value) + " point(s) de vie.";
                break;
            case 1:
                endText = "Vous reculez de " + String.valueOf(value) + " case(s).";
                break;
            case 0:
                endText = "Vous avancez de " + String.valueOf(value) + " case(s).";
                break;
            default:
                throw new AssertionError();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelTop;
    private presentation.PanelCarte panelCarte1;
    private presentation.PanelCarte panelCarte2;
    private presentation.PanelCarte panelCarte3;
    // End of variables declaration//GEN-END:variables
}
